### ISSUE TITLE
Where do we put the styles?

### ISSUE THREAD

**Issue by phuongy** [fendersperth/fenders-website#24]
So I started converting things over to emotion in my PR #23 

One of the issues we should discuss moving forward is if should move the styles into their own file or keep them together with the react component.

Maybe something like this?

File structure
```
/components
  /Button
    index.js <-- react component
    styles.js <--emotion components
```

Importing the styles into the react component
```
import React from 'react'
import { ButtonWrapper, ...... } from './styles';

...
<ButtonWrapper>
...
</ButtonWrapper>
```

Thoughts?

**Comment by antonjb** [comment]
Personally I would go for a file structure like this

`
/components
  /Button
    button.js
    button.styled.js
`

It makes importing verbose but avoids having ten index files open and getting confused. But there probably wont be that many in this project so I'm ok either way.

**Comment by phuongy** [comment]
Yea I don't like having `import Button from '../components/Button/button'` but I get how that's confusing.... it happens to me often these days :(

**Comment by pzi** [comment]
At work we have something like: 

```
/components
  /Button
	index.js
    button.js
    button.styled.js
```

which is a combination of all the things I suppose.

**Comment by phuongy** [comment]
I like it. I will put in a PR and see what people think
